site_name: LAG
theme: mkdocs
plugins:
      - encryptcontent:
          global_password: 'bellman'
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Guidelines: res_guide.md
  - Method: res_meth.md  
  - Tools: tools.md
  - Server: serv.md
  - Paper Reading: ppr_rdg.md
  - Papers: 
    - Single-Agent RL: s_rl.md
    - Multi-Agent RL: m_rl.md
